### ISSUE TITLE
没有找到路径/siyuan-plugin-quick-script

### ISSUE THREAD

**Issue by TCOTC** [zuoez02/siyuan-plugin-keymap#2]
![image](https://github.com/zuoez02/siyuan-plugin-keymap/assets/78434827/b7e6416b-7800-4427-9930-0499de2bc112)

`/data/storage/petal/siyuan-plugin-quick-script/`

在工作空间没有找到这个路径，是要手动创建吗？

**Comment by zuoez02** [comment]
找一下/data/storage/petal/siyuan-plugin-keymap

**Comment by TCOTC** [comment]
找到这个文件了，但好像不起作用，是我的理解错了吗？
在 思源-设置-快捷键 中没有对应的快捷键设置
![mmexport1699861525048.png](https://github.com/zuoez02/siyuan-plugin-keymap/assets/78434827/fb988966-5d55-4200-81e7-fa480937893d)

![mmexport1699861530760.png](https://github.com/zuoez02/siyuan-plugin-keymap/assets/78434827/8c54bade-ce2a-4bc9-a0b0-a0799a6bc394)

![mmexport1699861523316.png](https://github.com/zuoez02/siyuan-plugin-keymap/assets/78434827/3074d72d-8d3a-4ad1-bc3c-4165bba459bf)

**Comment by zuoez02** [comment]
把第一行删掉，那个是样例。如果要配置多个，把所有内容都放在一个[]里，这是JSON格式的数组。

**Comment by TCOTC** [comment]
成功了，感谢╰(*´︶`*)╯

**Comment by fulu-sys** [comment]
<img width="1333" height="984" alt="Image" src="https://github.com/user-attachments/assets/fe429244-81a5-4d1f-990d-b03ae4975c29" />

<img width="1340" height="985" alt="Image" src="https://github.com/user-attachments/assets/fea86a03-2be2-41f6-ba09-ff212d4797ee" />

<img width="1340" height="985" alt="Image" src="https://github.com/user-attachments/assets/55de02b1-3d04-44d7-92d2-c655e7fd0b31" />
为什么我找不到
